use lamp;

CREATE TABLE IF NOT EXISTS ships
(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
numComponents INT NOT NULL DEFAULT 0,
created DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS components
(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(32),
x FLOAT,
y FLOAT,
state TINYINT,
properties VARCHAR(255) NOT NULL DEFAULT '1',
ship INT UNSIGNED NOT NULL REFERENCES ships(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS connections
(
src INT UNSIGNED NOT NULL REFERENCES components(id) ON DELETE CASCADE,
dst INT UNSIGNED NOT NULL REFERENCES components(id) ON DELETE CASCADE,
PRIMARY KEY (src, dst),
INDEX (dst)
);

CREATE USER IF NOT EXISTS 'nonprivileged' IDENTIFIED BY 'nonprivileged';

GRANT INSERT, UPDATE, SELECT ON lamp.ships TO 'nonprivileged';
GRANT INSERT, UPDATE, SELECT ON lamp.components TO 'nonprivileged';
GRANT INSERT, SELECT ON lamp.connections TO 'nonprivileged';

FLUSH PRIVILEGES;
